version: 0.2

env:
  parameter-store:
    DOCKER_LOGIN_PASSWORD: /Test/helloWorld

phases:
  install:
    commands: 
      - wget -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl
      - chmod +x /usr/local/bin/kubectl
  pre_build: 
    commands:
      - aws --version
  build:
    commands:
      - echo build
      - pwd
  post_build:
    commands:
      - echo post_build
