version: 0.2

env: 
  variables: 
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    TEST: ${{ secrets.TEST }}
  parameter-store:
    DOCKER_UERNAME: /Test/helloWorld

phases:
  install:
    commands: 
      - wget -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl
      - chmod +x /usr/local/bin/kubectl
  pre_build: 
    commands:
      - aws --version
      - echo $TEST
  build:
    commands:
      - echo build
  post_build:
    commands:
      - echo post_build
