version: 0.2

env: 
  variables: 
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
  parameter-store:
    DOCKER_UERNAME: /Test/helloWorld

phases:
  install:
    commands: 
      - echo $DOCKER_UERNAME
  pre_build: 
    commands:
      - echo pre_build
  build:
    commands:
      - echo build
  post_build:
    commands:
      - echo post_build
