version: 0.2

env:
  variables:
    DOCKER_USER: "outautauo"
    DOCKER_PASS: "hogehoge"
  parameter-store:
    DOCKER_LOGIN_PASSWORD: /Test/helloWorld

phases:
  install:
    commands: 
      - echo testdayo
  pre_build: 
    commands:
      - aws --version
  build:
    commands:
      - echo build
      - pwd
      - less dev/buildspec_dev.yml
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
